### ISSUE TITLE
meta-messenger bot username is incorrect

### ISSUE THREAD

**Issue by pm-McFly** [mautrix/docs#68]
I suspect the username of the bot for Messenger administration is wrong here:
https://github.com/mautrix/docs/blob/f41ba06018eed136502c72d6b6b3f094461dfc28/bridges/go/meta/authentication.md?plain=1#L2

`@messengerbot::your.server`, might be the correct one.

**Comment by tulir** [comment]
The username can be whatever you want so there's no correct one. That's why it says "Usually"
